### ISSUE TITLE
Process and apply combination on windows agents

### ISSUE THREAD

**Issue by TomHoekstra** [redhat-developer/openshift-vsts#130]
When I try to run the following command:
process <template-name> -n <namespace> -p SOURCE_REPOSITORY_REF=$(Build.SourceBranchName) | apply -f -
I get the following error:
[command]D:\Tools\oc\oc.exe process autorisatie-api-build -n dt-postkamer-development -p SOURCE_REPOSITORY_REF=openshift | apply -f -
error: template name must be specified only once: |

The same happens when I try to export the output of a process statement to a .yaml with the following statement.
oc process -f template.yaml --local  -p -o yaml > output.yaml
For some reason it is not possible to use | or > symbols.

**Comment by lstocchi** [comment]
Thanks for your feedback @TomHoekstra I'll look into it. Let you know asap.

**Comment by lstocchi** [comment]
Hi @TomHoekstra , i gave a quick look and the toolrunner doesn't execute | or > operator in the right way. Still not sure how to solve this in the extension but one hack could be to use a script task and run the oc command from there. 
Something like
```
- task: oc-setup@2
  inputs:
    openshiftService: 'My Openshift'
    version: '3.11.154'
# A script task making use of 'oc'    
- script: |
    oc process -f template.yaml --local -p -o yaml > output.yaml
```
Let me know if this doesn't work for you. 

I'll reply as soon as I have a proper solution. This could be tricky because i don't know if we can make oc toolrunner works with pipe and redirection operators. Otherwise we should give the option to users to set up their own output variable from the task and call it in some script, but i don't think we can set up the variable name programmatically and this could lead to some other issues.
