### ISSUE TITLE
oc setup task with corporate proxy

### ISSUE THREAD

**Issue by ediri** [redhat-developer/openshift-vsts#89]
Hi there,

we have a corporate proxy set on our hosted agen and when we use the oc setup task in Azure DevOps we get following:

`request to https://api.github.com/repos/openshift/origin/releases/latest failed, reason: getaddrinfo ENOTFOUND api.github.com api.github.com:443`

Is there a way to set a proxy to the task?

**Comment by lstocchi** [comment]
Hi @ediri, sorry for the late response. Do you still have this error?
Have you tried to set a proxy environment variable such as http_port/https_port?
In your pipeline you should have something like 
```
- bash: export http_proxy="user:pass@my.proxy.server:port"
- bash: export https_proxy="user:pass@my.proxy.server:port"
- task: oc-setup@2
  inputs:
    openshiftService: 'My Openshift'
    version: 'v3.11.0'
```
I wasn't able to reproduce your exact error but this workaround worked for a different issue. Let us know if it works for you too.
