### ISSUE TITLE
Using oc-cmd in a deployment job fails

### ISSUE THREAD

**Issue by andersteern** [redhat-developer/openshift-vsts#90]
When using this task in a deployment job (in a multi stage yaml pipeline) gives the error:
"Job Job1: Step oc-cmd has an invalid name. Valid names may only contain alphanumeric characters and '_' and may not start with a number."

Using the old "jobs" works just fine with the oc-cmd task:

```
- stage: Openshift
  dependsOn: []
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: none
    - task: oc-cmd@2
      inputs:
        openshiftService: 'OpenShift'
        cmd: 'apply -n NNN -f deploy.yaml'
```

However, changing to the new deployment jobs gives the error above

```
- stage: Openshift
  dependsOn: []
  jobs:
  - deployment:
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - task: oc-cmd@2
            inputs:
              openshiftService: 'OpenShift'
              cmd: 'apply -n NNN -f deploy.yaml'
 ```
